apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongo-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
parameters:
  fsType: ext4
  type: gp2