apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: my-app
  labels:
    name: mongo
spec:
  replicas: 3
  selector:
    matchLabels:
      name: mongo
  template:
    metadata:
      labels:
        name: mongo
    spec:
      volumes:
        - name: mongo-db
          persistentVolumeClaim:
            claimName: mongo-storage
      containers:
        - nameterr: mongo
          image: mongo
          ports:
            - name: mongo
              containerPort: 27017
              protocol: TCP
          volumeMounts:
            - name: mongo-db
              mountPath: /mnt/data/db