apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: my-app
  labels:
    name: mongo
spec:
  ports:
    - protocol: TCP
      port: 27017
  selector:
    name: mongo
  type: LoadBalancer