apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-storage
  namespace: my-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
#  volumeName: mongo-pv
  storageClassName: mongo-sc
#  volumeMode: Filesystem