apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pacman-kubernetes.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pacman-kubernetes.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pacman-kubernetes.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pacman-kubernetes.selectorLabels" . | nindent 8 }}
        name: pacman
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: quay.io/ifont/pacman-nodejs-app:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          env:
            - name: MONGO_SERVICE_HOST
              value: mongo
            - name: MONGO_AUTH_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: mongodb-users-secret
            - name: MONGO_AUTH_PWD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: mongodb-users-secret
            - name: MONGO_DATABASE
              value: pacman
            - name: MY_MONGO_PORT
              value: "27017"
            - name: MONGO_USE_SSL
              value: "false"
            - name: MONGO_VALIDATE_SSL
              value: "false"
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName