apiVersion: v1
kind: Service
metadata:
  name: {{ include "pacman-kubernetes.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pacman-kubernetes.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "pacman-kubernetes.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo