apiVersion: v1
kind: Service
metadata:
  name: pac-man
  namespace: my-app
  labels:
    name: pac-man
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    name: pac-man
  type: LoadBalancer