apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pacman-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    name: pac-man
spec:
  selector:
    matchLabels:
      {{- include "pacman-kubernetes.selectorLabels" . | nindent 6 }}
  minAvailable: 100%